[general]
import = ["~/.config/alacritty/themes/themes/nightfly.toml"]

[window]
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 16.0
