[general]
import = ["~/.config/alacritty/themes/themes/nightfly.toml"]

[window]
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 14.0

